# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2))
arr



array([[1, 2, 3],
       [4, 5, 6]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [6]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
arr


array([[1, 4],
       [2, 5],
       [3, 6]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [8]:
arr = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr1 = arr.flatten()
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [10]:
arr = np.random.randint(100,size=(5,5,5))
arr.flatten()


array([24, 10, 99, 84, 77,  7, 38, 33, 28, 75, 67, 81, 38, 92, 72, 87, 27,
       52, 43, 29, 54, 98, 85, 73, 28, 92, 49, 32, 15, 97, 17, 17,  0,  1,
       68, 75, 30, 45, 59, 64, 91, 15, 17,  2, 64, 58, 31, 26, 57, 20,  8,
       61, 69, 21, 90, 26,  8, 90, 90,  7,  8, 52, 70, 77, 64, 44, 10, 47,
       67, 87, 51, 59, 71, 14, 48, 44, 61, 91, 97, 87, 57, 28, 24,  1, 50,
        5, 77, 66, 61, 93,  1, 49, 40, 85,  4, 82, 79, 77, 43,  3, 20, 69,
        8, 14, 56, 43, 14, 72, 82, 93, 16, 44,  3, 77, 84,  1, 17, 76, 17,
       99, 25, 16, 90, 15, 93])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [12]:
array = np.array([12, 98, 50, 93, 29, 64, 84, 68, 96,  4, 29, 55, 23, 96, 88, 75, 42,
       76, 78, 10, 18, 75, 51, 55,  5, 85, 45, 29, 33, 99, 65, 76, 96, 71,
       64, 31, 39, 42, 67, 31, 19, 30, 74, 47, 66, 86, 38,  7, 67, 81, 13,
       89, 81, 59,  9, 10, 82, 90, 27, 45,  6, 15,  1, 47,  0, 57, 39,  1,
       10, 19, 55, 47,  2, 17, 68, 55, 87, 76, 50, 97,  1, 99, 64, 51, 99,
       51, 67,  7, 31, 31,  7, 36, 66, 76, 62, 56, 29, 72, 82, 38, 79, 22,
        6, 30, 10, 11, 17, 97, 33, 12,  6, 53, 92, 53, 92, 65, 17, 95, 31,
       25, 22, 83, 51, 72, 22])
array.reshape(5,5,5)

array([[[12, 98, 50, 93, 29],
        [64, 84, 68, 96,  4],
        [29, 55, 23, 96, 88],
        [75, 42, 76, 78, 10],
        [18, 75, 51, 55,  5]],

       [[85, 45, 29, 33, 99],
        [65, 76, 96, 71, 64],
        [31, 39, 42, 67, 31],
        [19, 30, 74, 47, 66],
        [86, 38,  7, 67, 81]],

       [[13, 89, 81, 59,  9],
        [10, 82, 90, 27, 45],
        [ 6, 15,  1, 47,  0],
        [57, 39,  1, 10, 19],
        [55, 47,  2, 17, 68]],

       [[55, 87, 76, 50, 97],
        [ 1, 99, 64, 51, 99],
        [51, 67,  7, 31, 31],
        [ 7, 36, 66, 76, 62],
        [56, 29, 72, 82, 38]],

       [[79, 22,  6, 30, 10],
        [11, 17, 97, 33, 12],
        [ 6, 53, 92, 53, 92],
        [65, 17, 95, 31, 25],
        [22, 83, 51, 72, 22]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [14]:
array = np.random.rand(5,5)
np.square(array)

array([[7.24252948e-01, 4.11721228e-01, 3.48448007e-01, 9.36219699e-01,
        2.97663801e-01],
       [3.79799318e-01, 1.78110161e-01, 9.49286246e-05, 2.71739053e-01,
        4.79765699e-01],
       [4.69928231e-01, 2.31475203e-01, 6.71428776e-02, 1.25280627e-04,
        4.44410810e-01],
       [7.69238689e-02, 7.98892774e-04, 5.95599135e-05, 2.04618548e-01,
        1.95766117e-01],
       [2.31182616e-01, 8.11322868e-01, 1.16358670e-01, 2.21674615e-02,
        6.58055156e-01]])

## Question:8

### Create 5x6 an array and find the mean?

In [16]:
array = np.random.rand(5,5)
np.mean(array)

0.4856325837108917

## Question:9

### Find the standard deviation of the previous array in Q8?

In [18]:
np.std(array)

0.29281085520540373

## Question:10

### Find the median of the previous array in Q8?

In [20]:
np.median(array)

0.509015799369574

## Question:11

### Find the transpose of the previous array in Q8?

In [22]:
np.transpose(array)

array([[0.74548393, 0.06574893, 0.06800593, 0.89634332, 0.59406072],
       [0.23013308, 0.94211292, 0.5090158 , 0.05549669, 0.59554979],
       [0.8259735 , 0.40671459, 0.63051561, 0.90325542, 0.21140585],
       [0.74398295, 0.38270343, 0.16053176, 0.64853577, 0.31183074],
       [0.06147843, 0.89029065, 0.1931611 , 0.47456198, 0.59392169]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [24]:
arr4 = np.random.rand(4,4)
np.trace(arr4)

1.7550309947010627

## Question:13

### Find the determinant of the previous array in Q12?

In [26]:
np.linalg.det(arr4)

-0.006315653133707198

## Question:14

### Find the 5th and 95th percentile of an array?

In [35]:
array = np.ndarray(20)
print(np.percentile(array,5))
print(np.percentile(array,95))

-1.4697831496893348
1.2420252818154323


## Question:15

### How to find if a given array has any null values?

In [39]:
arr = np.array([0, 1, 2, 3, 4, -5])
sqrt_arr = np.sqrt(arr)
np.isnan(sqrt_arr)


array([False, False, False, False, False,  True])